version: "3.9"

services:

  # 1) Flask-app(web)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sre_web
    ports:
      - "5000:5000"
    networks:
      - sre_net

  # 2) Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: sre_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - sre_net

  # 3) Alertmanager
  alertmanager:
    image: prom/alertmanager:latest
    container_name: sre_alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    networks:
      - sre_net

  # 4) Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: sre_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - sre_net

  # 5) Телеграм-bot
  alert-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: sre_alert_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8080:8080"
    networks:
      - sre_net
    depends_on:
      - alertmanager

volumes:
  grafana-storage:

networks:
  sre_net:
    driver: bridge
