version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
  alert-bot:
    image: metalmatze/alertmanager-bot
    ports:
      - "8080:8080"
    depends_on:
      - alertmanager
    command:
      - --alertmanager.url=http://alertmanager:9093
      - --telegram.token=8116847685:AAE2OY6mrjnB1bhyE1KlfULdCsZ_3_37aGg
      - --telegram.admin=1278711614
      - --store=bolt

volumes:
  grafana-storage:
