---
- name: Clone or update SRE-final repository
  git:
    repo: "https://github.com/Dari4ok/SRE-final.git"
    dest: "/opt/sre"
    version: main
    force: yes

- name: Copy .env (with TELEGRAM_TOKEN, TELEGRAM_CHAT_ID) to /opt/sre
  copy:
    src: "{{ playbook_dir }}/../.env"
    dest: "/opt/sre/.env"
    owner: root
    group: root
    mode: '0600'

- name: Ensure all configuration files are present in /opt/sre
  copy:
    src: "{{ playbook_dir }}/../docker-compose.yml"
    dest: "/opt/sre/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'

- name: Copy prometheus.yml to /opt/sre
  copy:
    src: "{{ playbook_dir }}/../prometheus.yml"
    dest: "/opt/sre/prometheus.yml"
    owner: root
    group: root
    mode: '0644'

- name: Copy alert.rules.yml to /opt/sre
  copy:
    src: "{{ playbook_dir }}/../alert.rules.yml"
    dest: "/opt/sre/alert.rules.yml"
    owner: root
    group: root
    mode: '0644'

- name: Copy alertmanager.yml to /opt/sre
  copy:
    src: "{{ playbook_dir }}/../alertmanager.yml"
    dest: "/opt/sre/alertmanager.yml"
    owner: root
    group: root
    mode: '0644'

- name: Copy bot/ folder to /opt/sre
  copy:
    src: "{{ playbook_dir }}/../bot"
    dest: "/opt/sre/bot"
    owner: root
    group: root
    mode: '0755'

- name: Run docker-compose up -d in /opt/sre
  shell: docker-compose up -d
  args:
    chdir: "/opt/sre"

- name: Wait for containers to start
  pause:
    seconds: 10

- name: Check running containers
  shell: docker ps --format "{{ '{{' }}.Names {{ '}}' }}"
  register: running_containers

- name: Show container names
  debug:
    msg: "{{ running_containers.stdout_lines }}"
