---
- name: install Docker
  apt:
    name:
      - docker.io
    state: present

- name: install docker-compose
  apt:
    name: docker-compose
    state: present

- name: Checking docker procces
  service:
    name: docker
    state: started
    enabled: yes
